// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LogRecord struct {
	_tab flatbuffers.Table
}

func GetRootAsLogRecord(buf []byte, offset flatbuffers.UOffsetT) *LogRecord {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LogRecord{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LogRecord) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LogRecord) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LogRecord) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LogRecord) Value() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LogRecord) MutateValue(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func LogRecordStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LogRecordAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func LogRecordAddValue(builder *flatbuffers.Builder, value int64) {
	builder.PrependInt64Slot(1, value, 0)
}
func LogRecordEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
